<span style='color:gray'> <span style="font-size:30px;"> 
**Selection of Data for "Predictive model (ML)"**

<span style='color:gray'> <span style="font-size:20px;"> 
**Importing Libraries, Regressors, and Required Dependencies**

In [1]:
"""%pip install --quiet --upgrade scikit-learn==1.2.2
%pip install --quiet qbstyles"""

# Importing the dependencies
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib_inline.backend_inline import set_matplotlib_formats
set_matplotlib_formats('svg')
import matplotlib.patches as mpatches  # To create a legend with a color box

import os  # Import the os module to work with file paths

from qbstyles import mpl_style
mpl_style(dark=False)  # Set light matplotlib style


# Regression metrics
from sklearn.metrics import r2_score, mean_squared_error, mean_squared_error, mean_absolute_error

<span style='color:gray'> <span style="font-size:20px;"> 
**Loading datafile that has been extracted from DLIS file after (Sorting, Cleaning, preprocessing, choosing the logs based on need logically ...)**

<span style='color:gray'> <span style="font-size:15px;"> 
**3-BRSA-944A-RJS**

In [34]:
file_path = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Output of well data, [unique dataframe creation]/df_944_ML.csv'
df_944_ML =  pd.read_csv(file_path)
df_944_ML.rename(columns={'CMFF': 'NMRFF', 'CMRP_3MS': 'NMREFF', 'TCMR': 'NMRTOT'}, inplace=True)
df_944_ML

,DEPTH,GR,AT10,AT30,AT90,RHOZ,NPHI,DTCO,PEFZ,NMRFF,NMREFF,NMRTOT
0,5485.6380,13.120711,1932.475000,970.666600,444.036830,2.924115,0.022865,50.923492,5.680130,0.049936,0.396358,0.396671
1,5485.7905,13.314984,1950.000000,939.755600,445.810850,2.925845,0.022605,50.924683,5.683527,0.049936,0.396358,0.396671
2,5485.9430,12.030705,1950.000000,911.149000,431.264280,2.924257,0.023538,51.101196,5.726338,0.049936,0.396358,0.396671
3,5486.0950,12.029197,1950.000000,683.007600,342.343700,2.920914,0.025995,51.304516,5.771926,0.049936,0.396358,0.396671
4,5486.2476,11.834923,1950.000000,697.314640,388.370400,2.916199,0.022624,52.082188,5.826449,0.049936,0.396358,0.396671
...,...,...,...,...,...,...,...,...,...,...,...,...
3429,6008.2180,38.224780,42.018140,22.247396,10.556654,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3430,6008.3700,38.224780,42.056410,22.243960,10.582869,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3431,6008.5225,38.224780,42.117004,22.251312,10.609693,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3432,6008.6750,38.224780,42.145510,22.271675,10.631273,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3433,6008.8270,38.224780,42.154550,22.288443,10.644648,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654

=======================

<span style='color:gray'> <span style="font-size:15px;"> 
**1-BRSA-1116-RJS**

In [35]:
file_path = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Output of well data, [unique dataframe creation]/df_1116_ML.csv'
df_1116_ML =  pd.read_csv(file_path)
df_1116_ML.rename(columns={'CMFF': 'NMRFF', 'CMRP_3MS': 'NMREFF', 'TCMR': 'NMRTOT'}, inplace=True)
df_1116_ML

,DEPTH,GR,AT10,AT30,AT90,RHOZ,NPHI,DTCO,PEFZ,NMRFF,NMREFF,NMRTOT
0,5350.7640,29.228598,1880.636600,46.047977,65.436070,1.911232,0.462064,66.147160,10.000000,0.141804,0.399998,0.675131
1,5350.9165,28.384375,1803.976100,17.730986,45.512573,1.897772,0.493337,66.147160,10.000000,0.141804,0.399998,0.675131
2,5351.0690,25.366892,1557.294800,25.290165,35.453316,1.883895,0.503673,68.560080,10.000000,0.146237,0.430924,0.676864
3,5351.2210,21.658792,1227.168100,36.704130,48.546840,1.892580,0.383231,70.085560,10.000000,0.148821,0.464980,0.681370
4,5351.3735,20.227568,943.915340,30.725075,42.771717,1.915861,0.341551,70.682304,9.996842,0.143266,0.485577,0.667513
...,...,...,...,...,...,...,...,...,...,...,...,...
2900,5793.9434,44.209950,9.502799,9.016442,10.082510,2.714987,0.070175,66.917780,5.404206,0.011153,0.042941,0.049551
2901,5794.0957,44.209950,9.506191,9.060406,10.135521,2.714987,0.070175,66.917780,5.404206,0.011153,0.042941,0.049551
2902,5794.2480,44.209950,9.506411,9.106384,10.204328,2.714987,0.070175,66.917780,5.404206,0.011153,0.042941,0.049551
2903,5794.4004,44.209950,9.493680,9.064502,10.170754,2.714987,0.070175,66.917780,5.404206,0.011153,0.042941,0.049551
2904,5794.5527,44.209950,9.491426,9.017087,10.147186,2.714987,0.070175,66.917780,5.404206,0.011153,0.042941,0.049551

<span style='color:gray'> <span style="font-size:15px;"> 
**9-lTP-1-RJS**

In [36]:
file_path = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Output of well data, [unique dataframe creation]/df_9_ITP_ML.csv'
df_9_ITP_ML =  pd.read_csv(file_path)
df_9_ITP_ML

,DEPTH,GR,AT10,AT30,AT90,RHOZ,NPHI,DTCO,PEFZ,NMRFF,NMREFF,NMRTOT
0,5230.899893,18.364668,19.196234,20.528210,22.001585,2.112285,27.765093,68.337450,8.430419,14.694100,20.619087,27.914236
1,5230.999893,18.145609,17.247047,17.625770,18.691048,2.125317,28.151360,67.993440,8.418438,14.293544,20.741860,26.978453
2,5231.099893,17.943176,15.329754,15.300582,16.073359,2.130714,29.748737,67.663246,8.383753,13.796300,21.070040,26.331642
3,5231.199893,18.042002,11.579553,11.556740,11.997000,2.124417,31.248146,67.298560,8.239479,13.157555,21.527140,25.708328
4,5231.299893,18.240273,10.135851,10.116982,10.471834,2.124772,30.671698,66.678116,8.161089,12.434903,22.058117,25.103062
...,...,...,...,...,...,...,...,...,...,...,...,...
3691,5599.999899,69.719700,331.589630,233.684630,346.520800,2.558105,8.149640,63.348995,4.447030,1.574620,4.223740,4.802080
3692,5600.099899,75.163475,315.262180,223.281330,321.169250,2.556250,8.301083,63.904625,4.541373,1.357620,4.516560,5.014545
3693,5600.199899,75.267020,297.526600,212.320190,294.289520,2.563670,8.309896,64.537340,4.609696,1.087829,4.803412,5.407754
3694,5600.299899,73.839830,271.145540,194.598830,252.705150,2.596203,7.912412,65.022385,4.654750,1.087829,4.803412,5.407754
3695,5600.399899,67.758140,262.905030,189.417820,243.983690,2.613463,7.955445,65.515335,4.671908,1.087829,4.803412,5.407754

<span style='color:gray'> <span style="font-size:15px;"> 
**1-BRSA-1116-RJS**

## Seaborn PairPlot

A Seaborn pairplot is a multivariate visualization that shows the pairwise relationships between all numeric variables in a dataset. It is a grid of plots, with each row and column representing a different variable. The diagonal plots show the distribution of each variable, while the off-diagonal plots show the relationship between two variables.

The Seaborn pairplot can be used to explore the relationships between variables, identify outliers, and visualize the distribution of data. It is a powerful tool for data exploration and can be used to gain insights into complex datasets.

<span style='color:gray'> <span style="font-size:15px;"> 
**3-BRSA-944A-RJS**

In [5]:
sns.set_style('darkgrid')  # Setting the stying of the Seaborn figure

# Your code to create the pairplot
cols_to_plot = ['GR', 'RHGX_HILT', 'RHOZ', 'NPHI', 'PEFZ', 'CMRP_3MS', 'CMFF', 'TCMR']
pair_plot = sns.pairplot(df_944_ML[cols_to_plot], kind='reg', diag_kind='kde', plot_kws={'color':'blue','line_kws':{'color':'red'},
                                                                     'scatter_kws': {'s': 20, 'alpha': 0.5, 'edgecolor': 'white'}})
# Specify the folder where you want to save the image
output_folder = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Plots - data evaluation for selection'

# Ensure the folder exists, create it if necessary
os.makedirs(output_folder, exist_ok=True)

# Save the pairplot as an image (e.g., PNG)
output_filename = os.path.join(output_folder, 'pairplot-seaborn[3-BRSA-944A-RJS].png')  # Full path to the output file
pair_plot.savefig(output_filename)

plt.close(pair_plot.fig)

In [6]:
correlation_matrix = df_944_ML[cols_to_plot].corr()

#print(correlation_matrix)
correlation_matrix

,GR,RHGX_HILT,RHOZ,NPHI,PEFZ,CMRP_3MS,CMFF,TCMR
GR,1.000000,-0.289351,-0.026531,0.144441,-0.005881,-0.037447,-0.037446,-0.037445
RHGX_HILT,-0.289351,1.000000,0.482334,-0.386373,0.430577,-0.555441,-0.555442,-0.555444
RHOZ,-0.026531,0.482334,1.000000,-0.191118,0.743429,-0.732198,-0.732199,-0.732198
NPHI,0.144441,-0.386373,-0.191118,1.000000,-0.182572,0.095378,0.095378,0.095379
PEFZ,-0.005881,0.430577,0.743429,-0.182572,1.000000,-0.747797,-0.747798,-0.747797
CMRP_3MS,-0.037447,-0.555441,-0.732198,0.095378,-0.747797,1.000000,1.000000,1.000000
CMFF,-0.037446,-0.555442,-0.732199,0.095378,-0.747798,1.000000,1.000000,1.000000
TCMR,-0.037445,-0.555444,-0.732198,0.095379,-0.747797,1.000000,1.000000,1.000000

<span style='color:gray'> <span style="font-size:15px;"> 
**1-BRSA-1115-RJS**

In [7]:
sns.set_style('darkgrid')  # Setting the stying of the Seaborn figure

# Your code to create the pairplot
cols_to_plot = ['GR', 'AT10', 'AT30', 'AT90', 'CVEL', 'SSVE', 'NPHI', 'CMRP_3MS', 'CMFF', 'TCMR']
#'DTCO3'

pair_plot = sns.pairplot(df_1115_ML[cols_to_plot], kind='reg', diag_kind='kde', plot_kws={'color':'blue','line_kws':{'color':'red'},
                                                                     'scatter_kws': {'s': 20, 'alpha': 0.5, 'edgecolor': 'white'}})

# Specify the folder where you want to save the image
output_folder = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Plots - data evaluation for selection'

# Ensure the folder exists, create it if necessary
os.makedirs(output_folder, exist_ok=True)

# Save the pairplot as an image (e.g., PNG)
output_filename = os.path.join(output_folder, 'pairplot-seaborn[1-BRSA-1115-RJS].png')  # Full path to the output file
pair_plot.savefig(output_filename)

plt.close(pair_plot.fig)

In [8]:
correlation_matrix = df_1115_ML[cols_to_plot].corr()

#print(correlation_matrix)
correlation_matrix

,GR,AT10,AT30,AT90,CVEL,SSVE,NPHI,CMRP_3MS,CMFF,TCMR
GR,1.000000,0.179323,-0.079884,-0.136083,0.638105,0.305826,0.539565,0.043316,0.013878,-0.141615
AT10,0.179323,1.000000,0.105750,0.070962,0.390808,0.465039,0.129778,-0.092569,-0.086665,-0.172758
AT30,-0.079884,0.105750,1.000000,0.782612,0.026295,0.114367,-0.115125,0.075650,0.125994,0.008854
AT90,-0.136083,0.070962,0.782612,1.000000,-0.016926,0.178938,-0.214059,0.153117,0.215702,0.084720
CVEL,0.638105,0.390808,0.026295,-0.016926,1.000000,0.555298,0.690400,0.004807,-0.181285,-0.341724
SSVE,0.305826,0.465039,0.114367,0.178938,0.555298,1.000000,0.190436,0.139549,0.051102,-0.086541
NPHI,0.539565,0.129778,-0.115125,-0.214059,0.690400,0.190436,1.000000,-0.249415,-0.313749,-0.522211
CMRP_3MS,0.043316,-0.092569,0.075650,0.153117,0.004807,0.139549,-0.249415,1.000000,0.736184,0.824021
CMFF,0.013878,-0.086665,0.125994,0.215702,-0.181285,0.051102,-0.313749,0.736184,1.000000,0.648728
TCMR,-0.141615,-0.172758,0.008854,0.084720,-0.341724,-0.086541,-0.522211,0.824021,0.648728,1.000000

<span style='color:gray'> <span style="font-size:15px;"> 
**1-BRSA-1116-RJS**

In [9]:
sns.set_style('darkgrid')  # Setting the stying of the Seaborn figure

# Your code to create the pairplot
cols_to_plot = ['GR', 'SP', 'RHOZ', 'RHGX_HILT', 'AT10', 'AT30', 'AT90', 'NPHI', 'CMRP_3MS', 'CMFF', 'TCMR']
#'DTCO'

pair_plot = sns.pairplot(df_1116_ML[cols_to_plot], kind='reg', diag_kind='kde', plot_kws={'color':'blue','line_kws':{'color':'red'},
                                                                     'scatter_kws': {'s': 20, 'alpha': 0.5, 'edgecolor': 'white'}})

# Specify the folder where you want to save the image
output_folder = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Plots - data evaluation for selection'

# Ensure the folder exists, create it if necessary
os.makedirs(output_folder, exist_ok=True)

# Save the pairplot as an image (e.g., PNG)
output_filename = os.path.join(output_folder, 'pairplot-seaborn[1-BRSA-1116-RJS].png')  # Full path to the output file
pair_plot.savefig(output_filename)

plt.close(pair_plot.fig)

In [10]:
correlation_matrix = df_1116_ML[cols_to_plot].corr()

#print(correlation_matrix)
correlation_matrix

,GR,SP,RHOZ,RHGX_HILT,AT10,AT30,AT90,NPHI,CMRP_3MS,CMFF,TCMR
GR,1.000000,0.431113,-0.291504,-0.467768,-0.149788,-0.390299,-0.153208,0.103312,-0.230767,-0.230767,-0.230771
SP,0.431113,1.000000,-0.376021,-0.224960,0.087310,-0.211207,-0.052838,-0.053143,-0.497911,-0.497915,-0.497914
RHOZ,-0.291504,-0.376021,1.000000,0.387851,-0.156282,0.461048,0.111688,-0.033454,0.461961,0.461966,0.461962
RHGX_HILT,-0.467768,-0.224960,0.387851,1.000000,0.134556,0.601921,0.188780,-0.122311,0.037375,0.037381,0.037381
AT10,-0.149788,0.087310,-0.156282,0.134556,1.000000,0.206772,0.101824,-0.110281,-0.190654,-0.190656,-0.190656
AT30,-0.390299,-0.211207,0.461048,0.601921,0.206772,1.000000,0.195865,-0.126423,0.180184,0.180187,0.180187
AT90,-0.153208,-0.052838,0.111688,0.188780,0.101824,0.195865,1.000000,-0.103203,0.042290,0.042294,0.042293
NPHI,0.103312,-0.053143,-0.033454,-0.122311,-0.110281,-0.126423,-0.103203,1.000000,0.014195,0.014195,0.014195
CMRP_3MS,-0.230767,-0.497911,0.461961,0.037375,-0.190654,0.180184,0.042290,0.014195,1.000000,1.000000,1.000000
CMFF,-0.230767,-0.497915,0.461966,0.037381,-0.190656,0.180187,0.042294,0.014195,1.000000,1.000000,1.000000
TCMR,-0.230771,-0.497914,0.461962,0.037381,-0.190656,0.180187,0.042293,0.014195,1.000000,1.000000,1.000000

Plotting Specific Columns

Apply Depth Filtering

=========

In [37]:
df_Fin = pd.concat([df_944_ML, df_1116_ML, df_9_ITP_ML]).sort_values(by='DEPTH')
#df_Fin = df_Fin.drop_duplicates(subset='DEPTH')
#df_Fin.reset_index(drop=True, inplace=True)
df_Fin # Print the combined dataframe

,DEPTH,GR,AT10,AT30,AT90,RHOZ,NPHI,DTCO,PEFZ,NMRFF,NMREFF,NMRTOT
0,5230.899893,18.364668,19.196234,20.528210,22.001585,2.112285,27.765093,68.337450,8.430419,14.694100,20.619087,27.914236
1,5230.999893,18.145609,17.247047,17.625770,18.691048,2.125317,28.151360,67.993440,8.418438,14.293544,20.741860,26.978453
2,5231.099893,17.943176,15.329754,15.300582,16.073359,2.130714,29.748737,67.663246,8.383753,13.796300,21.070040,26.331642
3,5231.199893,18.042002,11.579553,11.556740,11.997000,2.124417,31.248146,67.298560,8.239479,13.157555,21.527140,25.708328
4,5231.299893,18.240273,10.135851,10.116982,10.471834,2.124772,30.671698,66.678116,8.161089,12.434903,22.058117,25.103062
...,...,...,...,...,...,...,...,...,...,...,...,...
3429,6008.218000,38.224780,42.018140,22.247396,10.556654,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3430,6008.370000,38.224780,42.056410,22.243960,10.582869,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3431,6008.522500,38.224780,42.117004,22.251312,10.609693,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3432,6008.675000,38.224780,42.145510,22.271675,10.631273,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654
3433,6008.827000,38.224780,42.154550,22.288443,10.644648,2.211345,0.090613,59.398567,9.907986,0.056437,0.067626,0.067654

Convert the DataFrame into a CSV file (CSV file is required for ML Algorithms implementation)

In [24]:
destination_file_path = '/Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Output of well data, [unique dataframe creation]/df_Fin.csv'

df_Fin.to_csv(destination_file_path, index=None)

print(f"DataFrame saved as CSV file at: {destination_file_path}")

DataFrame saved as CSV file at: /Users/amirhosseinakhondzadeh/CODE_WELLLOGS/Petrobras Well-log Analysis/Processed Data (out put of preprocessing == Input of ML)/Output of well data, [unique dataframe creation]/df_Fin.csv